# Generated by Django 3.2.3 on 2021-05-19 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prod_pubdate',
            new_name='Publish_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_desc',
            new_name='prod_Description',
        ),
    ]
