# Generated by Django 3.2.3 on 2021-05-19 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210519_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Publish_date',
            new_name='publish_date',
        ),
    ]
