# Generated by Django 3.2.3 on 2021-05-30 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20210530_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag10',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tag6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tag7',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tag8',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tag9',
        ),
    ]
