# Generated by Django 3.2.3 on 2021-05-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210528_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='pub_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
